
itemtypes = {
    1: 'ITEM_TYPE_STATION',
    2: 'ITEM_TYPE_ROBOT',
    3: 'ITEM_TYPE_FRAME',
    4: 'ITEM_TYPE_TOOL',
    5: 'ITEM_TYPE_OBJECT',
    6: 'ITEM_TYPE_TARGET',
    8: 'ITEM_TYPE_PROGRAM',
    9: 'ITEM_TYPE_INSTRUCTION',
    10: 'ITEM_TYPE_PROGRAM_PYTHON',
    11: 'ITEM_TYPE_MACHINING',
    12: 'ITEM_TYPE_BALLBARVALIDATION',
    13: 'ITEM_TYPE_CALIBPROJECT',
    14: 'ITEM_TYPE_VALID_ISO9283'
}

